### ISSUE TITLE
lib/typescriptServices.js no longer exists in the main branch of microsoft/TypeScript

### ISSUE THREAD

**Issue by mcmillhj-wta** [basarat/typescript-script#16]
It was removed in https://github.com/microsoft/TypeScript/pull/51683. Is there another file we can use in its place?

**Comment by jakebailey** [comment]
See also https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes#typescript-50. `typescript.js` is the thing to use.

That being said, _nobody_ should be using the `lib` dir on the `main` branch of the TS repo; this is just the compiler we use to compile the compiler itself. It should never be depended on externally as it can be arbitrarily out of date or using an unreleased version of the compiler. Consider pulling from a CDN like unpkg or jsdelivr instead.

**Comment by mcmillhj-wta** [comment]
Thanks, @jakebailey. Will close this issue.
